### ISSUE TITLE
Create SVGs for todo page

### ISSUE THREAD

**Issue by riboney** [CSSG-Labs/flask-todo-app#8]
- [ ] Trash icon for removing todos
- [ ] Plus sign icon for adding todos
- [ ] Pencil icon for editing todos

The SVGs can be exported from the figma mockup - [link](https://www.figma.com/file/scnkSLO8k63moEYhXHwgyb/Todo-Flask-Design?node-id=0%3A1)
